id: A7E737BFC
base_file: f2BAD.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-19 18:03:07.232604
  last_modified_at: 2022-06-19 18:03:07.232617
